name: 'Bug Report'
description: "Report something that isn't working the way you expected"
title: 'bug: (fill in)'
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: Environment
      description: |
        Please tell us about how you're running this
      value: |
        git commit:
        node version:
        pnpm version:
        Operating System:
      validations:
        required: true
  - type: textarea
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What actually happened?
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request to implement a fix.
          required: false
  - type: textarea
    attributes:
      label: Additional comments
      description: Is there anything else that's important for us to know?
